

import Foundation

struct placesStruct {
    var name: String
    var textAbout: String
    var photo: String
    var latitude: String
    var longitude: String
    init(name: String, textAbout: String, photo: String, latitude: String, longitude: String ) {
        self.name = name
        self.photo = photo
        self.latitude = latitude
        self.longitude = longitude
        self.textAbout = textAbout
    }
}


var arrayPlaces = [
    placesStruct(name: "The Getty Center", textAbout: "  The Getty Center, in Los Angeles, California, is a campus of the Getty Museum and other programs of the Getty Trust. The $1.3 billion Center opened to the public on December 16, 1997 and is well known for its architecture, gardens, and views overlooking Los Angeles. The Center sits atop a hill connected to a visitors' parking garage at the bottom of the hill by a three-car, cable-pulled hovertrain people mover.Located in the Brentwood neighborhood of Los Angeles, the Center is one of two locations of the J. Paul Getty Museum and draws 1.8 million visitors annually.",  photo: "The Getty Center", latitude: "34.078337", longitude: "-118.473758"),
    placesStruct(name: "Griffith Observatory", textAbout: "  A public observatory owned and operated by the City of Los Angeles for the benefit of all. Located in on Mount Hollywood in Griffith Park, the Observatory offers a planetarium, exhibits, public telescopes, cafe, bookstore, and the best views of the Los Angeles basin. Admission is free, and visitors may drive directly to the Observatory and park in its lots and roads.",  photo: "Griffith Observatory", latitude: "34.118546", longitude: "-118.300581"),
    placesStruct(name: "Universal Studios Hollywood", textAbout: "  Get ready for the ultimate Hollywood experience! Find a full day of action-packed entertainment all in one place: thrilling theme park rides and shows, a real working movie studio, and Los Angeles’ best shops, restaurants and cinemas at CityWalk. Universal Studios Hollywood is a unique experience that’s fun for the whole family. Explore Universal Studios backlot on the legendary Studio Tour. Then face the action head on in heart-pounding rides, shows and attractions that put you inside some of the world’s biggest movies. End your day with the energy and excitement of Universal CityWalk. ",  photo: "Universal Studios Hollywood", latitude: "34.137919", longitude: "-118.353474"),
    placesStruct(name: "Petersen Automotive Museum", textAbout: "  Rated the #1 Automotive museum in the world, the Petersen Automotive Museum is dedicated to the exploration and presentation of the automobile and its impact on Global life and culture. The museum features 25 galleries with more than 350 vehicles on display between the main floors and exclusive Vault. Visitors can immerse themselves in the 1000's of stories on display in the museum through tactile interactives, videos, and hands-on learning experiences in the Pixar Discovery Center.",  photo: "Petersen Automotive Museum", latitude: "34.062456", longitude: "-118.361364"),
    placesStruct(name: "Battleship USS Iowa Museum", textAbout: "  The Battleship IOWA Museum is a Top 10 regional attraction, consistently rated as a must-see experience. Named as a “Best Cool Exhibits to See With Your Kids” by CBS Los Angeles, there are behind-the-scenes tours or a self-guided adventure interacting with veterans and/or using your mobile device highlighting life on-board for thousands of sailors during the last 70 years. If visitors decide the latter, they can interact with the National Battleship Museum exhibits using our state of the art, award-winning interactive app.",  photo: "Battleship USS Iowa Museum", latitude: "33.742126", longitude: "-118.277735"),
    placesStruct(name: "Griffith Park", textAbout: "  Griffith Park is a large municipal park at the eastern end of the Santa Monica Mountains, in the Los Feliz neighborhood of Los Angeles, California. The park covers 4,310 acres (1,740 ha) of land, making it one of the largest urban parks in North America. It is the second-largest city park in California, after Mission Trails Preserve in San Diego, and the 11th largest municipally owned park in the United States. It has also been referred to as the Central Park of Los Angeles but is much larger, more untamed, and rugged than its New York City counterpart.",  photo: "Griffith Park", latitude: "34.135964", longitude: "-118.293976"),
    placesStruct(name: "The Broad", textAbout: "  The Broad is a new contemporary art museum founded by philanthropists Eli and Edythe Broad on Grand Avenue in downtown Los Angeles. The museum is designed by Diller Scofidio + Renfro and offers free general admission. The museum is home to the 2,000 works of art in the Broad collection, which is among the most prominent holdings of postwar and contemporary art worldwide. General admission to The Broad is free.",  photo: "The Broad", latitude: "34.054320", longitude: "-118.250101"),
    placesStruct(name: "Staples Center", textAbout: "  It is owned and operated by the Arturo L.A. Arena Company and Anschutz Entertainment Group. The arena is home to the Los Angeles Kings of the National Hockey League (NHL), the Los Angeles Lakers and the Los Angeles Clippers of the National Basketball Association (NBA), and the Los Angeles Sparks of the Women's National Basketball Association (WNBA). The Los Angeles Avengers of the Arena Football League (AFL) and the Los Angeles D-Fenders of the NBA D-League were also tenants",  photo: "Staples Center", latitude: "34.043695", longitude: "-118.265948"),
    placesStruct(name: "Los Angeles County Museum of Art", textAbout: "  Since its inception in 1965, the Los Angeles County Museum of Art (LACMA) has been devoted to collecting works of art that span both history and geography, in addition to representing Los Angeles's uniquely diverse population. Today LACMA is the largest art museum in the western United States, with a collection that includes over 120,000 objects dating from antiquity to the present, encompassing the geographic world and nearly the entire history of art.",  photo: "Los Angeles County Museum of Art", latitude: "34.063884", longitude: "-118.359247"),
    placesStruct(name: "Walt Disney Concert Hall", textAbout: "  The Walt Disney Concert Hall at 111 South Grand Avenue in downtown Los Angeles, California, is the fourth hall of the Los Angeles Music Center and was designed by Frank Gehry. It opened on October 24, 2003. Bounded by Hope Street, Grand Avenue, and 1st and 2nd Streets, it seats 2,265 people and serves, among other purposes, as the home of the Los Angeles Philharmonic orchestra and the Los Angeles Master Chorale. The hall is a compromise between an arena seating configuration, like the Berliner Philharmonie by Hans Scharoun, and a classical shoebox design like the Vienna Musikverein or the Boston Symphony Hall.",  photo: "Walt Disney Concert Hall", latitude: "34.055196", longitude: "-118.249788"),
    placesStruct(name: "Madame Tussauds Hollywood", textAbout: "  Madame Tussauds Hollywood is a wax museum and tourist attraction located on Hollywood Boulevard in Hollywood, California. It is the ninth location for the Tussauds franchise, which was set up by sculptor Marie Tussaud, and is located just west of the TCL Chinese Theatre (formerly Grauman's). Madame Tussauds is owned and operated by Merlin Entertainments.    ",  photo: "Madame Tussauds Hollywood", latitude: "34.101916", longitude: "-118.341590"),
    placesStruct(name: "Dodger Stadium", textAbout: "  Dodger Stadium, occasionally called by the metonym Chavez Ravine, is a baseball park located in the Elysian Park neighborhood of Los Angeles, California, the home field to the Los Angeles Dodgers, the city's National League franchise of Major League Baseball (MLB). Opened 57 years ago on April 10, 1962, it was constructed in less than three years at a cost of US$23 million, financed by private sources. Dodger Stadium is currently the oldest ballpark in MLB west of the Mississippi River, and is the world's largest baseball stadium by seat capacity. The stadium has seen twelve no-hitters, two of which were perfect games.  ",  photo: "Dodger Stadium", latitude: "34.072888", longitude: "-118.240043"),
    placesStruct(name: "Hollywood Sign", textAbout: "  Perched atop Mount Lee, this global symbol of Hollywood glamour measures 450 feet in length with mammoth white letters, each standing 45 feet high, spelling out the name of the city. There is no access to The Hollywood Sign as it sits on restricted property however; there are several scenic view points which provide great photo opportunities . 1) Hollywood and Highland. Farther away but easy , especially if you are already in Hollywood. 2) The Griffith Observatory. Take the Metro Red Line at Hollywood and Highland to the Griffith Observatory stop. ",  photo: "Hollywood Sign", latitude: "34.134119", longitude: "-118.321669"),
    placesStruct(name: "Universal CityWalk Hollywood", textAbout: "  Universal CityWalk is the name shared by the entertainment and retail districts located adjacent to the theme parks of Universal Parks & Resorts. CityWalk began as an expansion of Universal's first park, Universal Studios Hollywood, and serves as an entrance plaza from the parking lots to the theme parks. CityWalk can also be found at Universal Orlando Resort in Florida and Universal Studios Japan in Osaka, Japan.CityWalk Hollywood and CityWalk Orlando have some common tenants, but their respective architectural styles are quite different. Where CityWalk Hollywood incorporates a classic modern blend of Hollywood, CityWalk Orlando is almost entirely modern in appearance.",  photo: "Universal CityWalk Hollywood", latitude: "34.135951", longitude: "-118.351261"),
    placesStruct(name: "University of California, Los Angeles (UCLA)", textAbout: "  The University of California, Los Angeles (UCLA), is a public research university in Los Angeles. It became the Southern Branch of the University of California in 1919, making it the fourth-oldest (after UC Berkeley, UC San Francisco, and UC Davis) of the 10-campus University of California system. It offers 337 undergraduate and graduate degree programs in a wide range of disciplines. UCLA enrolls about 31,000 undergraduate and 13,000 graduate students and had 119,000 applicants for Fall 2016.",  photo: "University of California, Los Angeles (UCLA)", latitude: "34.069019", longitude: "-118.446082"),
    placesStruct(name: "Abbot Kinney Boulevard", textAbout: "  Abbot Kinney is a mile long stretch of popular shops, restaurants, and galleries located in the Southern Part of Venice, California. It stretches from Venice Boulevard to Pacific Avenue and is home to one-of-kind local goods as well as internationally recognized brands. Abbot Kinney Boulevard is named after Abbot Kinney, the 19th century millionaire entrepreneur. In 2012, GQ magazine called Abbot Kinney “The Coolest Block in America.” The streets on Abbot Kinney are filled with International flagship stores and boho-beach chic boutiques, art galleries, salons, and several fitness choices such as rope climbing",  photo: "Abbot Kinney Boulevard", latitude: "33.989959", longitude: "-118.463883"),
    placesStruct(name: "The Hollywood Museum", textAbout: "  The Hollywood Museum, the official museum of Hollywood located in the Historic Max Factor Building, spotlights the Legends of Hollywood with the most extensive collection of authentic Hollywood memorabilia in the World. The museum features four floors of breathtaking exhibits and is the home of more than 10,000 authentic Showbiz Treasures, one-of-a-kind costumes, props, photographs, scripts and vintage collectibles from favorite movies and TV shows. The Hollywood Museum is a 501(c)(3) non-profit organization.",  photo: "The Hollywood Museum", latitude: "34.101080", longitude: "-118.338501"),
    placesStruct(name: "Jet Propulsion Laboratory", textAbout: "  The Jet Propulsion Laboratory (JPL) is a federally funded research and development center and NASA field center in La Cañada Flintridge, California, United States, though it is often referred to as residing in Pasadena, California, because it has a Pasadena ZIP Code.Founded in the 1930s, the JPL is currently owned by NASA and managed by the nearby California Institute of Technology (Caltech) for NASA. The laboratory's primary function is the construction and operation of planetary robotic spacecraft, though it also conducts Earth-orbit and astronomy missions.",  photo: "Jet Propulsion Laboratory", latitude: "34.182568", longitude: "-118.162336"),
    placesStruct(name: "City of Pasadena City Hall", textAbout: "  In 1923, the people of Pasadena approved a bond measure issuing $3.5 million towards the development of a civic center. City Hall was to be the central element of this center. The San Francisco architecture firm of Bakewell and Brown designed City Hall, which has elements of both Mediterranean Revival Style and Spanish Colonial Revival Style architecture. It was completed on December 27, 1927 at a cost of $1.3 million. It measures 361 feet (110 m) by 242 feet (74 m), and rises 6 stories. There are over 235 rooms and passageways that cover over 170,000 square feet (16,000 m2).",  photo: "City of Pasadena City Hall", latitude: "34.147652", longitude: "-118.143834"),
    placesStruct(name: "California Institute of Technology", textAbout: " The California Institute of Technology (Caltech) is a private doctorate-granting research university in Pasadena, California.Known for its strength in natural science and engineering, Caltech is often ranked as one of the world's top-ten universities. Although founded as a preparatory and vocational school by Amos G. Throop in 1891, the college attracted influential scientists such as George Ellery Hale, Arthur Amos Noyes and Robert Andrews Millikan in the early 20th century.",  photo: "California Institute of Technology", latitude: "34.137365", longitude: "-118.125891"),
    placesStruct(name: "Museum of Jurassic Technology", textAbout: "  The Museum of Jurassic Technology at 9341 Venice Boulevard in the Palms district of Los Angeles, California, was founded by David Hildebrand Wilson and Diana Drake Wilson (husband and wife) in 1988. It calls itself 'an educational institution dedicated to the advancement of knowledge and the public appreciation of the Lower Jurassic', the relevance of the term 'Lower Jurassic' to the museum's collections being left uncertain and unexplained.",  photo: "Museum of Jurassic Technology", latitude: "34.181923", longitude: "-118.273329"),
    placesStruct(name: "Santa Anita Race Park", textAbout: "  Santa Anita Park is a Thoroughbred racetrack in Arcadia, California, United States. It offers some of the prominent horse racing events in the United States during the winter and in spring. The track is home to numerous prestigious races including both the Santa Anita Derby and the Santa Anita Handicap as well as hosting the Breeders' Cup in 1986, 1993, 2003, 2008, 2009, 2012, 2013, 2014, 2016 and will host in 2019. Since 2011, The Stronach Group are the current owners.    ",  photo: "Santa Anita Race Park", latitude: "34.138090", longitude: "-118.045212"),
    placesStruct(name: "Angels Flight Railway", textAbout: "  Angels Flight is a landmark 2 ft 6 in (762 mm) narrow gauge funicular railway in the Bunker Hill district of Downtown Los Angeles, California. It has two funicular cars, Sinai and Olivet, running in opposite directions on a shared cable on the 298 feet (91 m) long inclined railway. The funicular has operated on two different sites, using the same cars and station elements. The original Angels Flight location, with tracks connecting Hill Street and Olive Street, operated from 1901 until it was closed in 1969, when its site was cleared for redevelopment. ",  photo: "Angels Flight Railway", latitude: "34.051272", longitude: "-118.250180"),
    placesStruct(name: "Vincent Price Art Museum", textAbout: "  The Vincent Price Art Museum (VPAM) is an art museum located at East Los Angeles College in Monterey Park, CA. The museum is named after American actor Vincent Price who donated portions of his personal art collection to the college in 1957. The museum's collection now contains over 9,000 objects ranging from impressionist paintings to Japanese prints to objects from the Ancient Americas, 2,000 of which were donated by Price. The museum has been an important space for underrepresented artists since its founding, organizing key solo exhibitions for Los Angeles based artists. ",  photo: "Vincent Price Art Museum", latitude: "34.038716", longitude: "-118.146974"),
    placesStruct(name: "Hollywood Forever Cemetery", textAbout: "  Hollywood Forever Cemetery is one of the oldest cemeteries in Los Angeles, California. Located at 6000 Santa Monica Boulevard in the Hollywood district of Los Angeles, it was founded in 1899 as Hollywood Cemetery, and later known as Hollywood Memorial Park until 1998 when it was given its current name. The studios of Paramount Pictures are located at the south end of the same block, on 40 acres (16 ha). Individuals interred in the cemetery include many prominent people from the entertainment industry, as well as people who played vital roles in shaping Los Angeles. ",  photo: "Hollywood Forever Cemetery", latitude: "34.088706", longitude: "-118.319271"),
    placesStruct(name: "Hollywood Bowl Museum", textAbout: "  The Hollywood Bowl is an amphitheater in the Hollywood Hills neighborhood of Los Angeles, California. It was named one of the 10 best live music venues in America by Rolling Stone Magazine in 2018.The Hollywood Bowl is known for its band shell, a distinctive set of concentric arches that graced the site from 1929 through 2003, before being replaced with a larger one beginning in the 2004 season. The shell is set against the backdrop of the Hollywood Hills and the famous Hollywood Sign to the northeast.The 'bowl' refers to the shape of the concave hillside the amphitheater is carved into. ",  photo: "Hollywood Bowl Museum", latitude: "34.112051", longitude: "-118.337464"),
    placesStruct(name: "Dolby Theatre", textAbout: "  The Dolby Theatre (formerly known as the Kodak Theatre) is a live-performance auditorium in the Hollywood and Highland Center shopping mall and entertainment complex, on Hollywood Boulevard and Highland Avenue, in the Hollywood district of Los Angeles. Since its opening on November 9, 2001, the theater has been the venue of the annual Academy Awards ceremony. It is adjacent to the Grauman's Chinese Theatre and the El Capitan Theatre nearby on Hollywood Boulevard.    ",  photo: "Dolby Theatre", latitude: "34.102895", longitude: "-118.340767"),
    placesStruct(name: "City Hall", textAbout: "  Los Angeles City Hall, completed in 1928, is the center of the government of the city of Los Angeles, California, and houses the mayor's office and the meeting chambers and offices of the Los Angeles City Council. It is located in the Civic Center district of downtown Los Angeles in the city block bounded by Main, Temple, First, and Spring streets.    ",  photo: "City Hall", latitude: "34.053985", longitude: "-118.243210"),
    placesStruct(name: "Los Angeles Central Library", textAbout: "  The Los Angeles Public Library system (LAPL) serves the residents of the City of Los Angeles. The system holds more than six million volumes, and with over 18 million residents in the Los Angeles Metropolitan area, it serves the largest population of any publicly funded library system in the United States. The system is overseen by a Board of Library Commissioners with five members appointed by the mayor of Los Angeles in staggered terms in accordance with the city charter.    ",  photo: "Los Angeles Central Library", latitude: "34.050046", longitude: "-118.255208"),
    placesStruct(name: "Cathedral of Our Lady of the Angels", textAbout: "  The Cathedral of Our Lady of the Angels (Spanish: Catedral de Nuestra Señora de los Ángeles), informally known as COLA or the Los Angeles Cathedral, is a cathedral of the Roman Catholic Church in Los Angeles, California, United States of America. Opened in 2002, it serves as the mother church for the Archdiocese of Los Angeles,as well as the seat of Archbishop José Horacio Gómez. The structure replaced the Cathedral of Saint Vibiana, which was severely damaged in the 1994 Northridge earthquake.",  photo: "Cathedral of Our Lady of the Angels", latitude: "34.058024", longitude: "-118.245392"),
    placesStruct(name: "GRAMMY Museum", textAbout: "  The GRAMMY Museum is an interactive space where all aspects of music are experienced, explored, and celebrated. We break down the barrier between artist and audience, telling stories of how music has shaped our collective identity and cultural understanding. By deconstructing the creative process, considering music makers through a broader social lens, and placing you in the creator role, our thought-provoking exhibits and programs showcase the storied legacy of music—the thread that connects us.    ",  photo: "GRAMMY Museum", latitude: "34.044523", longitude: "-118.264549"),
    placesStruct(name: "Center For Motion Picture Study", textAbout: "  The Pickford Center for Motion Picture Study is one of three Los Angeles-area facilities of the Academy of Motion Picture Arts and Sciences, located at 1313 Vine Street in central Hollywood.The Pickford Center for Motion Picture Study was named in honor of legendary silent film actress Mary Pickford in 2002. Pickford was one of the founding members of the Academy.In addition to the 286-seat Linwood Dunn Theater where numerous public events are presented throughout the year, the building houses several Academy departments. ",  photo: "Center For Motion Picture Study", latitude: "34.094437", longitude: "-118.327828")
]

let textInfoLabel = "This application was written for tourists and local residents of Los Angeles. These places are required to visit! You can build a tourist route to the main attractions using the second screen. On the third screen you can offer an interesting place! Fill out the form and send it to us. If we like it too, then all users will see this place. You can also add your places in your application on the fourth screen. It will immediately appear on the map in your app."


struct myPlacesStruct {
    var text: String
    var longitude: String
    var latitude: String
    
    init(text: String, longitude: String, latitude: String) {
        self.text = text
        self.longitude = longitude
        self.latitude = latitude
    }
}

